module.exports = {

    login:{
        title:'登录',
        requiredParameters:{}
    },
    contact:{
        title:'联系我们',
    },
    productExample:{
        title:'项目案例'
    },
    news:{
        title:'新闻资讯'
    },
    introduction:{
        title:'公司介绍'
    },
    products:{
        title:'产品展示'
    },
    productList:{
        title:'产品列表'
    },
    productDetail:{
        title:'产品详情'
    },

    contact_mobile:{
        title:'联系我们',
    },
    productExample_mobile:{
        title:'项目案例'
    },
    news_mobile:{
        title:'新闻资讯'
    },
    introduction_mobile:{
        title:'公司介绍'
    },
    products_mobile:{
        title:'产品展示'
    },
    productList_mobile:{
        title:'产品列表'
    },
    productDetail_mobile:{
        title:'产品详情'
    },
};
